import { ButtonSounds, DropdownBoxSounds } from 'vuetale/types/elements';
export declare const Vars: {
    ButtonsMainActivate: () => string;
    ButtonsMainHover: () => string;
    ButtonsMain: () => ButtonSounds;
    ButtonsLightActivate: () => string;
    ButtonsLightHover: () => string;
    ButtonsLight: () => ButtonSounds;
    ButtonsCancelActivate: () => string;
    ButtonsCancel: () => ButtonSounds;
    CosmeticsTilesActivate: () => string;
    CosmeticsTiles: () => ButtonSounds;
    DropdownBox: () => DropdownBoxSounds;
    EnterWorldActivate: () => string;
    EnterWorld: () => ButtonSounds;
    FriendsList: () => {};
    HButtonHover: () => string;
    Lock: () => ButtonSounds;
    Unlock: () => ButtonSounds;
    SaveActivate: () => string;
    SaveSettings: () => ButtonSounds;
    Respawn: () => string;
    RespawnActivate: () => ButtonSounds;
    ServerList: () => ButtonSounds;
    ShuffleActivate: () => string;
    Shuffle: () => ButtonSounds;
    Tick: () => string;
    Untick: () => string;
    TopBarActivate: () => string;
    TopBar: () => ButtonSounds;
};
